# Generated by Django 4.1.1 on 2022-09-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('first_name',)},
        ),
    ]
