# Generated by Django 4.1.1 on 2022-09-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_post_image_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatar1.jpg', upload_to='profile_pic'),
        ),
    ]
